### ISSUE TITLE
Allowing prefixes in replaced assets

### ISSUE THREAD

**Issue by simonc** [dlepaux/fingerprint-brunch#41]
Hi there 👋 

I'm trying to use fingerprint-brunch in a jekyll project where I placed my files like this
```
_assets/images/logo.svg
_assets/stylesheeps/app.scss
```

the CSS contains something like
```scss
.logo {
  background-image: url('logo.svg');
}
```

my goal is to have final files placed like this
```
assets/app-d12a3f93.css
assets/logo-b23d91f8.svg
```
with the CSS containing
```css
.logo {
  background-image: url('/assets/logo-b23d91f8.svg');
}
```
but right now the configuration will not allow for assets prefixing and the replacement will end up being
```css
.logo {
  background-image: url('/logo-b23d91f8.svg');
}
```

Would you be interested in a PR adding a `prefix` option that would be prepended after _public_ has been removed from the images path? It would also open the door to prepending a CDN url or other ideas.

I'd be open to suggestions regarding the option's name as "prefix" is not very explicit but this idea would be

```js
exports.plugins = {
  fingerprint: {
    autoReplaceAndHash: true,
    prefix: '/assets'
  }
};
```

Cheers! ❤️
